# Generated by Django 5.0.7 on 2025-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acao', 'Ação'), ('fundoimobiliario', 'Fundo Imobiliário'), ('rendafixa', 'Renda Fixa'), ('eua', 'Estados Unidos')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
        ),
    ]
