# Generated by Django 5.0.7 on 2025-09-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_investimentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investimentos',
            new_name='Investimento',
        ),
    ]
