# Generated by Django 5.0.7 on 2025-09-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_investimentos_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='ativo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
