# Generated by Django 5.2.7 on 2025-12-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_investimento_ativo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investimento',
        ),
    ]
