# Generated by Django 5.2.7 on 2025-12-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
